version: "3.8"

services:
  frontend:
    image: keshab232002/ai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: keshab232002/ai-backend
    ports:
      - "127.0.0.1:2000:2000"
    env_file:
      - ./backend/.env
